version: "3.1"
services:
  web:
    build: ./smartLockApi
    volumes:
      - ./smartLockApi:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis  # Added dependency on the Redis service

  frontend:
    build: ./samrtLockApp
    volumes:
      - ./samrtLockApp:/app
    ports:
      - 3000:3000
    depends_on:
      - web

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: smartLock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3101
      PGDATA: /data/postgres
    ports:
      - "5433:5432"
    restart: unless-stopped

  redis:
    container_name: redis_container
    image: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

